server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:    gateway:      routes:      - id: stockMarket
        uri: http://localhost:8085/        predicates:        - Path=/api/v1.0/market/company/**
      - id: stockMicroservice
        uri: http://localhost:8086/
        predicates:        - Path=/api/v1.0/market/stock/**
        
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
        