server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:    gateway:      routes:      - id: companyService
        uri: lb://company-service        predicates:        - Path=/api/v1.0/market/company/**
      - id: stockService
        uri: lb://stock-service
        predicates:        - Path=/api/v1.0/market/stock/**
  security:    user:      name: riya
      password: riya@123
        
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
      
        